# Usar uma imagem base do Python 3.10
FROM python:3.10

RUN pip install poetry

WORKDIR /api

COPY . .

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

EXPOSE 5000

CMD ["flask", "run"]